# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Extract python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Extract python version 3.8
      run: echo `python -c "import sys;print(sys.version)"` > python_version_3.8.txt
    - name: Upload Versions
      uses: actions/upload-artifact@v3
      with:
        name: python-artifact 3.8
        path: python_version_3.8.txt
      
      
    - name: Extract python version 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Extract python version 3.9
      run: echo `python -c "import sys;print(sys.version)"` > python_version_3.9.txt
    - name: Upload Versions
      uses: actions/upload-artifact@v3
      with:
        name: python-artifact 3.8
        path: python_version_3.8.txt
      
      
    - name: Extract python version 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Extract python version 3.10
      run: echo `python -c "import sys;print(sys.version)"` > python_version_3.10.txt
    - name: Upload Versions
      uses: actions/upload-artifact@v3
      with:
        name: python-artifact 3.8
        path: python_version_3.8.txt
      
    

